[package]
name = "maze-maker"
version = "2.1.1"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]
edition = "2018"

[dependencies]
maze = { path = "../maze" }
maze-tools = { path = "../tools" }
clap = "2.31"
image = "0.18"
rand = "*"
rayon = "1.0"
svg = "0.5"
