[package]
name = "maze-maker"
version = "3.0.1"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]
edition = "2021"

[dependencies]
maze = { path = "../maze" }
maze-tools = { path = "../tools" }
clap = "2.33"
image = "0.23"
rand = "*"
rayon = "1.3"
svg = "0.10"
