[package]
name = "labyru"
version = "0.1.0"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]

[dependencies]
rand = { version = "0.4", optional = true }
svg = { version = "0.5", optional = true }

[features]
default = ["osrand", "render-svg"]
osrand = ["rand"]
render-svg = ["svg"]
