[package]
name = "labyru"
version = "0.1.0"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]

[dependencies]
clap = "2.24.1"
rand = "0.3"
svg = { version = "0.5", optional = true }

[features]
default = ["render-svg"]
render-svg = ["svg"]
