[package]
name = "labyru"
version = "0.1.0"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]

[dependencies]
clap = "2.31"
image = { version = "0.18", optional = true }
rand = { version = "0.4", optional = true }
rayon = { version = "1.0", optional = true }
svg = { version = "0.5", optional = true }

[features]
default = ["background", "osrand", "parallel", "render-svg"]
background = ["image"]
osrand = ["rand"]
parallel = ["rayon"]
render-svg = ["svg"]
