[package]
name = "labyru-web"
version = "0.1.0"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]
edition = "2018"

[dependencies]
labyru = { path = "../labyru" }
rand = { version = "0.4" }
rocket = "0.4.0"
svg = { version = "0.5" }
