[package]
name = "maze-tools"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
maze = { path = "../maze" }

lazy_static = { workspace = true }
svg = { workspace = true, optional = true }


[features]
default = ["alphabet", "cell", "heatmap", "image", "svg", "voronoi"]
alphabet = []
cell = []
heatmap = []
image = []
svg = ["dep:svg"]
voronoi = []
