[package]
name = "maze-web"
version = "2.1.1"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]
edition = "2018"

[dependencies]
maze = { path = "../maze" }
actix-web = { version = "1.0" }
rand = "*"
serde = "*"
svg = "*"

[dev-dependencies]
serde_urlencoded = { version = "*" }
