[package]
name = "maze-web"
version = "3.0.1"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]
edition = "2021"

[dependencies]
maze = { path = "../maze" }
actix-web = "3"
futures-util = "*"
rand = "*"
serde = "*"
svg = "0.13"

[dev-dependencies]
serde_urlencoded = { version = "*" }
