[package]
name = "maze-web"
version = "3.0.0"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]
edition = "2018"

[dependencies]
maze = { path = "../maze" }
actix-web = "3.0"
futures-util = "*"
rand = "*"
serde = "*"
svg = "*"

[dev-dependencies]
serde_urlencoded = { version = "*" }
